# These are supported funding model platforms

github: [RabinApps] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
buy_me_a_coffee: rabinapps # Replace with a single Buy Me a Coffee username
custom: ['https://www.paypal.com/donate/?hosted_button_id=YEJ37WF4Q3HPC']# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
